name: Docker

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    strategy:
      matrix:
        include:
          - baseImageTag: '7.4'
            imageTag: '7.4'
          - baseImageTag: '7.4'
            imageTag: 7.4-debug
            xdebugVersion: '3.1.6'
          - baseImageTag: 7.4-apache
            imageTag: 7.4-apache
          - baseImageTag: 7.4-apache
            imageTag: 7.4-apache-debug
            xdebugVersion: '3.1.6'
          - baseImageTag: 7.4-fpm
            imageTag: 7.4-fpm
          - baseImageTag: 7.4-fpm
            imageTag: 7.4-fpm-debug
            xdebugVersion: '3.1.6'
          - baseImageTag: '8.3'
            imageTag: '8.3'
          - baseImageTag: '8.3'
            imageTag: 8.3-debug
            xdebugVersion: '3.3.2'
          - baseImageTag: 8.3-apache
            imageTag: 8.3-apache
          - baseImageTag: 8.3-apache
            imageTag: 8.3-apache-debug
            xdebugVersion: '3.3.2'
          - baseImageTag: 8.3-fpm
            imageTag: 8.3-fpm
          - baseImageTag: 8.3-fpm
            imageTag: 8.3-fpm-debug
            xdebugVersion: '3.3.2'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: v2.2.4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.imageTag }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          build-args: |
            baseImageTag=${{ matrix.baseImageTag }}
            xdebugVersion=${{ matrix.xdebugVersion }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max=

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
